#config_version=6

mode: 
  start_events: start_mode_ramp
  stop_events: stop_mode_ramp
  priority: 200

shots:
  ramp:
    switch: s_ramp

variable_player:
  ramp_hit:
    score: 5000
  mode_ramp_started:
    ramp_active:  
      int: 1
      action: set
  mode_ramp_stopped:
    ramp_active:  
      int: 0
      action: set