#config_version=6

# Attract mode that starts when the machine boots up, stops
# whenever a game is started, and re-starts after the game ends.

slide_player:
  mode_attract_started: attract

mode_settings:
  selectable_items:
    - title
    - credits
    - mpf_logo
  next_item_events: s_flipper_right_active
  previous_item_events: s_flipper_left_active

sound_player:
  mode_attract_started:
    hollow_knight_theme:
      bus: music
      loops: -1
  mode_attract_stopped:
    holloow_knight_theme:
      action: stop
