#config_version=6

# Attract mode that starts when the machine boots up, stops
# whenever a game is started, and re-starts after the game ends.

slide_player:
  mode_attract_started: attract

mode_settings:
  selectable_items:
    - title
    - map
    - credits
    - mpf_and_cobrapin_logo
    - team_cherry
  next_item_events: s_right_flipper_active, timer_attract_carousel_timer_complete
  previous_item_events: s_left_flipper_active

sound_player:
  mode_attract_started:
    hollow_knight_theme:
      bus: music
      loops: -1
  mode_attract_stopped:
    holloow_knight_theme:
      action: stop

timers:
  attract_carousel_timer:
    end_value: 1
    tick_interval: 5s
    start_running: true
    control_events:
      - event: timer_attract_carousel_timer_complete
        action: restart
      - event: item_highlighted
        action: restart
      - event: flipper_cradle
        action: stop
      - event: flipper_cradle_release
        action: restart