#config_version=6

# Base mode that starts at the beginning of each ball
# and stops at the end of each ball.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

event_player:
  mode_base_started:
    - start_mode_right_orbit
    - start_mode_slingshots
    - start_mode_lanes
    - stop_mode_vuk
    - start_mode_ramp
    - start_mode_left_orbit
    - start_mode_lane_to_pop
    - start_mode_saucer
    - start_mode_targets
  mode_base_will_stop:
    - stop_mode_right_orbit
    - stop_mode_slingshots
    - stop_mode_lanes
    - start_mode_vuk
    - stop_mode_ramp
    - stop_mode_left_orbit
    - stop_mode_lane_to_pop
    - stop_mode_saucer
    - stop_mode_targets

slide_player:
  mode_base_started: base