#config_version=6

# Base mode that starts at the beginning of each ball
# and stops at the end of each ball.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

event_player:
  mode_base_started:
    - start_mode_right_orbit
    - start_mode_slingshots
    - start_mode_lanes
    - start_mode_vuk
    - start_mode_ramp
    - start_mode_left_orbit
    - start_mode_lane_to_pop
    - start_mode_saucer
    - start_mode_targets
    - start_mode_pop_bumper
    - start_mode_dirtmouth
    - start_mode_mask_controller

  #Every mode needs to stop here
  mode_base_will_stop:
    - stop_mode_right_orbit
    - stop_mode_slingshots
    - stop_mode_lanes
    - stop_mode_vuk
    - stop_mode_ramp
    - stop_mode_left_orbit
    - stop_mode_lane_to_pop
    - stop_mode_saucer
    - stop_mode_targets
    - stop_mode_pop_bumper
    - stop_mode_dirtmouth
    - stop_mode_false_knight_controller
    - stop_mode_frogotten_crossroads
    - stop_mode_travel_dirtmouth_to_frogotten_crossroads
    - stop_mode_carousel_mode_select
    - stop_mode_mask_controller

slide_player:
  mode_base_started: base

sound_player:
  mode_attract_stopped:
    hollow_knight_theme:
      action: stop
  mode_dirtmouth_stopped:
    dirtmouth:
      action: stop
  mode_false_knight_controller_stopped:
    false_knight:
      action: stop
  mode_frogotten_crossroads_stopped:
    crossroads:
      action: stop


variable_player:
  mode_dirtmouth_stopped:
    dirtmouth_active:
      int: 0
      action: set
  mode_false_knight_controller_stopped:
    mode_active:
      int: 0
      action: set
  mode_lane_to_pop_stopped:
    lane_to_pop_active:
      int: 0
      action: set
  mode_frogotten_crossroads_stopped:
    frogotten_crossroads_active:
      int: 0
      action: set
  mode_lanes_stopped:
    lanes_active:
      int: 0
      action: set
  mode_left_orbit_stopped:
    left_orbit_active:
      int: 0
      action: set
  mode_pop_bumper_stopped:
    pop_bumper_active: 
      int: 0
      action: set
  mode_ramp_stopped:
    ramp_active:  
      int: 0
      action: set
  mode_right_orbit_stopped:
    right_orbit_active: 
      int: 0
      action: set
  mode_saucer_stopped:
    saucer_active:
      int: 0
      action: set
  mode_slingshots_stopped:
    slingshots_active:
      int: 0
      action: set
  mode_travel_dirtmouth_to_frogotten_crossroads_stopped:
    travel_progress:
      int: 0
      action: set
    mode_active:
      int: 0
      action: set
  mode_vuk_stopped:
    vuk_active:
      int: 0
      action: set
  mode_targets_stopped:
    targets_active:
      int: 0
      action: set