#config_version=6

mode:
  start_events: start_mode_right_orbit
  stop_events: stop_mode_right_orbit
  priority: 200

shots:
  right_orbit:
    switch: s_right_orbit

variable_player:
  right_orbit_hit:
    score: 5000
  mode_right_orbit_started:
    right_orbit_active: true
    action: set
  mode_right_orbit_stopped:
    right_orbit_active: false
    action: set