#config_version=6

mode:
  start_events: start_mode_carousel_mode_select
  stop_events: stop_mode_carousel_mode_select
  priority: 500
  code: mpf.modes.carousel.code.carousel.Carousel


mode_settings:
  selectable_items:
    - travel_dirtmouth_to_frogotten_crossroads{current_player.dirtmouth_active == 1 or current_player.frogotten_crossroads_active == 1}
    - false_knight_controller{current_player.frogotten_crossroads_active == 1}
    - leave
  select_item_events: flipper_cancel
  next_item_events: s_right_flipper_active
  previous_item_events: s_left_flipper_active


slide_player:
  mode_carousel_mode_select_started: carousel_mode_select


event_player:
  carousel_travel_dirtmouth_to_frogotten_crossroads_selected: 
    - start_mode_travel_dirtmouth_to_frogotten_crossroads
    - stop_mode_carousel_mode_select
  carousel_false_knight_controller_selected: 
    - start_mode_false_knight_controller
    - stop_mode_carousel_mode_select
  carousel_leave_selected: stop_mode_carousel_mode_select