#config_version=6

mode:
  start_events: start_mode_dirtmouth
  stop_events: stop_mode_dirtmouth
  priority: 250

slide_player:
  mode_dirtmouth_started: dirtmouth

sound_player:
  mode_dirtmouth_started:
    dirtmouth:
      bus: music
      loops: -1
  mode_dirtmouth_stopped:
    dirtmouth:
      action: stop

