#config_version=6

mode:
  start_events: start_mode_dirtmouth
  stop_events: stop_mode_dirtmouth
  priority: 250

slide_player:
  mode_dirtmouth_started: dirtmouth

sound_player:
  mode_dirtmouth_started:
    dirtmouth:
      bus: music
      loops: -1


shots:
  vuk_dirtmouth:
    switch: s_vuk
  saucer_dirtmouth: 
    switch: s_saucer

shot_groups:
  locks_dirtmouth: 
    shots: vuk_dirtmouth, saucer_dirtmouth

event_player:
  locks_dirtmouth_hit{current_player.mode_active == 0}: start_mode_carousel_mode_select

variable_player:
  mode_dirtmouth_started:
    dirtmouth_active:
      int: 1
      action: set
