#config_version=6

mode: 
  start_events: start_mode_pop_bumper
  stop_events: stop_mode_pop_bumper
  priority: 150

shots:
  pop_bumper:
    switch: s_pop_bumper

variable_player:
  pop_bumper_hit:
    score: 1110
  mode_pop_bumper_started:
    pop_bumper_active: 
      int: 1
      action: set