#config_version=6

mode: 
  start_events: start_mode_left_orbit
  stop_events: stop_mode_left_orbit
  priority: 200

shots:
  left_orbit:
    switch: s_left_orbit

variable_player:
  left_orbit_hit:
    score: 5000
  mode_left_orbit_started:
    left_orbit_active:
      int: 1
      action: set
  mode_left_orbit_stopped:
    left_orbit_active:
      int: 0
      action: set