#config_version=6

mode: 
  start_events: start_mode_slingshots
  stop_events: stop_mode_slingshots
  priority: 150

shots:
  top_left_slingshot:
    switch: s_top_left_slingshot
  bottom_left_slingshot:
    switch: s_bottom_left_slingshot
  top_right_slingshot:
    switch: s_top_right_slingshot
  bottom_right_slingshot:
    switch: s_bottom_right_slingshot

shot_groups:
  slingshots:
    shots: top_left_slingshot, bottom_left_slingshot, top_right_slingshot, bottom_right_slingshot

variable_player:
  slingshots_hit:
    score: 1000
  mode_slingshots_started:
    slingshots_active: true
    action: set
  mode_slingshots_stopped:
    slingshots_active: false
    action: set