#config_version=6

coils:
  c_flipper_left_main:
    number:
    default_pulse_ms: 
  c_flipper_left_hold:
    number:
    allow_enable: true
  c_flipper_right_main:
    number:
    default_pulse_ms:
  c_flipper_right_hold:
    number:
    allow_enable: true
  c_trough_eject:
    number:
    default_pulse_ms:

  #will need to be modified

  c_vuk_eject:
    number:
    default_pulse_ms:
  c_pop_bumper:
    number:
    default_pulse_ms:
  c_saucer_eject:
    number:
    default_pulse_ms: