#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

#Number is used once the board is wired up to assign the correct switch on the cobra pin
#For the coild the pulses will need to be adjusted
#Might need to adjust default coild hold strengths

#will probably need to add stough here
game:
  balls_per_game: 3

hardware:
  platform: smart_virtual #change this back to opp
  driverboards: gen2

config:
  - config_switches.yaml
  - config_coils.yaml
  - config_lights.yaml
  - config_ball_devices.yaml
  - config_player_variables.yaml

playfields:
  playfield:
    tags: default
    default_source_device: bd_trough

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper

modes:
  - attract
  - base
  - right_orbit
  - slingshots
  - lanes
  - vuk
  - ramp
  - left_orbit
  - lane_to_pop
  - saucer
  - targets
  - pop_bumper
  - dirtmouth
  - false_knight_controller



#Get rid of this when pushing to the game
virtual_platform_start_active_switches:
  - s_trough_1
  - s_trough_2
  - s_trough_3