#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

#Number is used once the board is wired up to assign the correct switch on the cobra pin
#For the coild the pulses will need to be adjusted
#Might need to adjust default coild hold strengths

hardware:
  platform: opp
  driverboards: gen2

switches:
  s_left_flipper:
    number: 
    tags: left_flipper
  s_right_flipper:
    number: 
    tags: right_flipper

#Trough switches will have to be reworked
  s_trough_1:
    number: 
  s_trough_2:
    number:
  s_trough_3:
    number:
  s_plunger_lane:
   number:

coils:
  c_flipper_left_main:
    number:
    default_pulse_ms: 
  c_flipper_left_hold:
    number:
    allow_enable: true
  c_flipper_right_main:
    number:
    default_pulse_ms:
  c_flipper_right_hold:
    number:
    allow_enable: true
  c_trough_eject:
    number:
    default_pulse_ms:


playfields:
  playfield:
    tags: default
    default_source_device: bd_trough

ball_devices:
  bd_trough:
    ball_switches: s_trough_1, s_trough_2, s_trough_3
    eject_coil: c_trough_eject
    eject_targets: bd_plunger
    tags: trough, home, drain
  bd_plunger:
    ball_switches: s_plunger_lane
    mechanical_eject: true

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper

modes:
  - attract
  - base