#config_version=6

mode: 
  start_events: start_mode_saucer
  stop_events: stop_mode_saucer
  priority: 200

shots:
  saucer:
    switch: s_saucer

variable_player:
  saucer_hit:
    score: 5000
  mode_saucer_started:
    saucer_active:
      int: 1
      action: set
  mode_saucer_stopped:
    saucer_active:
      int: 0
      action: set
  