#config_version=6

mode: 
  start_events: start_mode_lanes
  stop_events: stop_mode_lanes
  priority: 150

shots:
  left_outlane:
    switch: s_left_outlane
  left_inlane:
    switch: s_left_inlane
  right_inlane:
    switch: s_right_inlane
  right_outlane:
    switch: s_right_outlane
  
shot_groups:
  lanes:
    shots: left_outlane, left_inlane, right_inlane, right_outlane

variable_player:
  lanes_hit:
    score: 1000